coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 5%

# Flags for filtering coverage by test type
# The overall project score merges both automatically
flags:
  r:
    paths:
      - R/
      - src/
    carryforward: true
  cpp:
    paths:
      - src/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "R/RcppExports.R"
  - "src/RcppExports.cpp"
  - "tests/**"
  - "cpp_tests/**"
